// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfzufzajsybdgdlhjkie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1menVmemFqc3liZGdkbGhqa2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MDcxNTksImV4cCI6MjA4ODM4MzE1OX0.mmkrmquEkD_kuRg03SCamjeFWxsfmWU3-Q4FIVnot1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});